import { Link, useParams } from 'react-router-dom';
import { ArrowUpRight, ArrowDown, Mountain, ShieldCheck, Cable, ChevronLeft, CalendarDays, Clock3 } from 'lucide-react';
import { useContent } from '../App';
import { ParallaxImage, Reveal, Contact, DemoBadge, usePageTitle } from '../components';

export function TeamPage() {
  usePageTitle('川衡登山队');
  const { settings, projects } = useContent();
  return <div className="team-page"><section className="team-hero"><ParallaxImage src={settings.heroTeam} alt={settings.demoMode !== false ? '雪山与冰川的专业攀登示意影像' : '川衡登山队攀登影像'}/><div className="team-hero-shade"/><div className="container team-hero-content"><span className="eyebrow">CHUANHENG ALPINE TEAM</span><h1>向上，<br/>是我们的方向<span>。</span></h1><p>雪山攀登 / 专业领队 / 攀冰</p><a href="#team-intro" className="button button-outline light">走近登山队 <ArrowDown size={17}/></a><div className="team-hero-foot"><span>PREPARATION. TRUST. COMMITMENT.</span>{settings.demoMode !== false && <span>AI 生成示意影像</span>}</div></div></section>
    <section className="team-intro container" id="team-intro"><Reveal><div className="section-heading"><div><span className="eyebrow">01 / THE TEAM BEHIND THE CLIMB</span><h2>攀登之前，<br/>先成为一支队伍。</h2></div><p className="team-intro-description">{settings.teamDescription}</p></div></Reveal><div className="team-disciplines">{[{icon:Mountain,n:'01',title:'雪山攀登',en:'ALPINE CLIMBING',text:'通过体能、技术与协作训练，为专业高山实践做准备。'}, {icon:ShieldCheck,n:'02',title:'专业领队',en:'MOUNTAIN LEADERSHIP',text:'积累路线规划、队伍组织与户外带队能力。'}, {icon:Cable,n:'03',title:'攀冰与绳索',en:'ICE & ROPE SKILLS',text:'以系统学习和反复练习，走向更专业的技术领域。'}].map((item,i) => <Reveal key={item.n} delay={i*70}><div className="discipline-top"><span>{item.n}</span><item.icon size={29} strokeWidth={1.2}/></div><small>{item.en}</small><h3>{item.title}</h3><p>{item.text}</p></Reveal>)}</div></section>
    <section className="team-training"><div className="container training-grid"><Reveal><span className="eyebrow">BEFORE THE SUMMIT</span><h2>每一次向上，<br/>都有扎实的准备。</h2><div className="preserve-lines">{settings.teamTraining}</div>{settings.teamAchievements && <div className="team-achievements"><h3>训练与攀登记录</h3><div className="preserve-lines">{settings.teamAchievements}</div></div>}<Link to="/about" className="text-link">了解从社员到队员的成长路径 <ArrowUpRight size={17}/></Link></Reveal><div className="training-image"><ParallaxImage src={settings.storyClimbing} alt={settings.demoMode !== false ? '山地训练方向的攀登示意影像' : '登山队训练与准备'}/><span className="training-image-text">THE CLIMB<br/>STARTS HERE.</span></div></div></section>
    <section className="projects-section container" id="projects"><Reveal><div className="section-heading"><div><span className="eyebrow">02 / PROJECTS WORTH SUPPORTING</span><h2>下一座山，<br/>期待与你共赴。</h2></div><p>以具体攀登项目为起点，<br/>让支持拥有清晰的去向。</p></div></Reveal>{projects.length ? <div className="project-grid">{projects.map(project => <Reveal key={project.id}><Link className="project-card" to={`/projects/${project.id}`}><div className="project-image"><img src={project.image || settings.heroTeam} alt={`${project.title}的${project.isDemo?'示意':''}影像`}/>{project.isDemo && <DemoBadge/>}</div><div className="project-card-content"><span className="eyebrow">{project.mountain} {project.elevation && `/ ${project.elevation}`}</span><h3>{project.title}</h3><p>{project.summary}</p><span className="text-link">了解攀登计划与支持需求 <ArrowUpRight size={17}/></span></div></Link></Reveal>)}</div> : <Reveal><div className="project-empty"><div className="contour-art" aria-hidden="true"><Mountain size={70} strokeWidth={.8}/><span>THE NEXT CHAPTER</span></div><div><span className="eyebrow">未来攀登计划</span><h3>新的攀登项目，将在这里公布。</h3><p>当前暂无公开攀登项目。你可以先了解登山队的训练方向，或就未来项目与全年训练支持交流合作。</p><a href="#support" className="text-link">了解合作方向 <ArrowUpRight size={17}/></a></div></div></Reveal>}</section>
    <section className="support-section" id="support"><div className="container"><Reveal><div className="section-heading"><div><span className="eyebrow">03 / PARTNERSHIP</span><h2>你的支持，<br/>可以成为攀登的一部分。</h2></div><p>项目合作 · 装备支持 · 全年训练</p></div></Reveal><div className="support-grid">{[{n:'01',title:'单次攀登项目',text:'围绕明确的目标与计划，沟通项目经费、行程保障和专项支持。'}, {n:'02',title:'技术装备支持',text:'根据训练与攀登的实际需求，交流专业装备、器材与使用支持。'}, {n:'03',title:'全年训练合作',text:'支持持续的体能、技术与领队培养，让成长发生在日常训练中。'}].map(item => <Reveal key={item.n}><span>{item.n}</span><h3>{item.title}</h3><p>{item.text}</p></Reveal>)}</div><Reveal><div className="team-cooperation-link"><p>了解全部项目、合作权益与流程，<br/>下载一份完整的合作手册。</p><Link to="/cooperation" className="button">合作资料与手册 <ArrowUpRight size={17}/></Link></div></Reveal></div></section></div>;
}

export function ProjectDetail() {
  const { id } = useParams();
  const { projects, settings } = useContent();
  const project = projects.find(p => p.id === id);
  usePageTitle(project?.title || '攀登项目');
  if (!project) return <div className="not-found container"><h1>项目暂未公开。</h1><Link className="button button-green" to="/team">了解登山队</Link></div>;
  return <article className="detail-page"><div className="detail-header container"><Link to="/team" className="back-link"><ChevronLeft size={16}/> 川衡登山队</Link><div className="detail-tags"><span className="eyebrow">ALPINE PROJECT / 攀登计划</span>{project.isDemo && <DemoBadge/>}</div><h1>{project.title}</h1><p className="detail-lead">{project.summary}</p><div className="detail-facts"><span><Mountain size={18}/>{project.mountain}{project.elevation && ` · ${project.elevation}`}</span>{project.plannedDate && <span><CalendarDays size={18}/>{project.plannedDate}</span>}{project.duration && <span><Clock3 size={18}/>{project.duration}</span>}</div></div><div className="container detail-cover"><img src={project.image || settings.heroTeam} alt={`${project.title}项目影像`}/></div><div className="container project-detail-content">{[{label:'THE OBJECTIVE',title:'攀登目标与计划',text:project.description},{label:'PREPARATION',title:'训练与准备',text:project.trainingPlan},{label:'SUPPORT NEEDED',title:'项目支持需求',text:project.supportNeeds},{label:'PARTNERSHIP VALUE',title:'合作与共同价值',text:project.cooperationValue}].filter(s=>s.text).map(section=><Reveal key={section.label}><section className="prose"><span className="eyebrow">{section.label}</span><h2>{section.title}</h2><div className="preserve-lines">{section.text}</div></section></Reveal>)}{project.isDemo && <div className="demo-note">本项目为示意内容，请以登山队正式公布的计划为准。</div>}</div><section className="support-section"><div className="container"><Contact settings={settings}/></div></section></article>;
}
