import { useEffect, useRef, useState, type FormEvent, type KeyboardEvent } from 'react';
import { Plus, Pencil, Trash2, X, RefreshCw, ExternalLink, Image } from 'lucide-react';
import { api } from '../api';
import type { Activity, Project, PublicContent } from '../types';

type Entity=Activity|Project;
const emptyActivity:Activity={id:'',title:'',category:'徒步',kind:'upcoming',date:'',location:'',difficulty:'',summary:'',description:'',image:'',signupUrl:'',qrImage:'',status:'draft',isDemo:false,registrationOpen:false};
const emptyProject:Project={id:'',title:'',mountain:'',elevation:'',plannedDate:'',duration:'',summary:'',description:'',trainingPlan:'',supportNeeds:'',cooperationValue:'',image:'',status:'draft',isDemo:false};

function ImageField({label,value,onChange,onError,onBusy,canUpload}:{label:string;value:string;onChange:(value:string)=>void;onError:(message:string)=>void;onBusy:(busy:boolean)=>void;canUpload:boolean}) {
  const [uploading,setUploading]=useState(false);
  const picker=useRef<HTMLInputElement>(null);
  async function upload(file:File|undefined){if(!file||!canUpload)return;if(file.size>8*1024*1024){onError('图片须小于或等于 8 MB。');return;}setUploading(true);onBusy(true);try{const dataUrl=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result as string);reader.onerror=()=>reject(new Error('读取图片失败。'));reader.readAsDataURL(file);});const r=await api<{url:string}>('/admin/upload',{method:'POST',body:JSON.stringify({filename:file.name,dataUrl})});onChange(r.url);}catch(e){onError((e as Error).message);}finally{setUploading(false);onBusy(false);}}
  return <div className="admin-image-field"><label className="admin-field">{label}<input value={value} onChange={e=>onChange(e.target.value)} placeholder={canUpload?"图片地址，或上传图片":"已有图片地址"}/></label>{canUpload&&<><button type="button" className="admin-button admin-secondary" disabled={uploading} onClick={()=>picker.current?.click()}><Image size={16}/>{uploading?'正在上传…':'上传图片'}</button><input ref={picker} type="file" accept="image/jpeg,image/png,image/webp" disabled={uploading} onChange={e=>{void upload(e.target.files?.[0]);e.target.value='';}} hidden/></>}{value&&<img src={value} alt={`${label}预览`}/>}<small className="admin-help">{canUpload?'JPEG / PNG / WebP，单张不超过 8 MB。上传后保存内容即可应用。':'图片上传尚未授权，可以填写已有图片地址。'}</small></div>;
}

export function Records({kind,content,onSaved,onError,onReload,canUpload}:{kind:'activities'|'projects';content:PublicContent;onSaved:(next:PublicContent)=>void;onError:(message:string)=>void;onReload:()=>void;canUpload:boolean}) {
  const [editing,setEditing]=useState<Entity|null>(null),[dirty,setDirty]=useState(false),[busy,setBusy]=useState(false),[formError,setFormError]=useState(''),[filter,setFilter]=useState('all');
  const [uploads,setUploads]=useState(0);
  const modalRef=useRef<HTMLDivElement>(null);
  const trackUpload=(active:boolean)=>setUploads(value=>value+(active?1:-1));
  const list:Entity[]=content[kind];const isActivity=kind==='activities';
  const shown=list.filter(item=>filter==='all'||item.status===filter);
  function edit(item:Entity){setEditing({...item});setDirty(false);setFormError('');}
  function close(){if(busy||uploads)return;if(dirty&&!confirm('有未保存的修改，是否放弃？'))return;setEditing(null);setDirty(false);}
  useEffect(()=>{if(!editing)return;const previous=document.activeElement as HTMLElement;const overflow=document.body.style.overflow;document.body.style.overflow='hidden';modalRef.current?.querySelector<HTMLInputElement>('input:not([type="file"])')?.focus();return()=>{document.body.style.overflow=overflow;previous?.focus();};},[editing?.id]);
  function modalKeys(event:KeyboardEvent){if(event.key==='Escape'){event.stopPropagation();close();}if(event.key==='Tab'){const elements=Array.from(modalRef.current?.querySelectorAll<HTMLElement>('a[href],button:not([disabled]),input:not([disabled]):not([hidden]),select:not([disabled]),textarea:not([disabled])')||[]).filter(el=>el.offsetParent!==null);const first=elements[0],last=elements[elements.length-1];if(event.shiftKey&&document.activeElement===first){event.preventDefault();last?.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first?.focus();}}}
  function update(key:string,value:string|boolean){setEditing(prev=>prev?{...prev,[key]:value}:null);setDirty(true);}
  function field(label:string,key:string,options:{required?:boolean;type?:string;textarea?:boolean}={}) {const value=String((editing as unknown as Record<string,unknown>)?.[key]??'');return <label className="admin-field">{label}{options.textarea?<textarea required={options.required} value={value} onChange={e=>update(key,e.target.value)} rows={5}/>:<input type={options.type||'text'} required={options.required} value={value} onChange={e=>update(key,e.target.value)}/>}</label>;}
  async function save(e:FormEvent){e.preventDefault();if(!editing||uploads)return;setBusy(true);setFormError('');try{const result=await api<{activity?:Activity;project?:Project}>(`/admin/${kind}${editing.id?`/${editing.id}`:''}`,{method:editing.id?'PUT':'POST',body:JSON.stringify(editing)});const saved=result.activity||result.project;if(!saved)throw new Error('保存响应无效，请重新加载内容。');const next=[saved,...list.filter(item=>item.id!==saved.id)];onSaved({...content,[kind]:next});setDirty(false);setEditing(null);}catch(e){setFormError((e as Error).message);}finally{setBusy(false);}}
  async function remove(item:Entity){if(!confirm(`确认删除“${item.title}”？删除后将不再显示。`))return;setBusy(true);try{await api(`/admin/${kind}/${item.id}${item.revision?`?revision=${item.revision}`:''}`,{method:'DELETE'});onSaved({...content,[kind]:list.filter(a=>a.id!==item.id)});}catch(e){onError((e as Error).message);}finally{setBusy(false);}}
  return <section className="admin-panel"><div className="admin-toolbar"><div><h2>{isActivity?'活动预告与回顾':'攀登项目计划'}</h2><p className="admin-help">{isActivity?'按预告或回顾维护，报名入口可使用单次活动链接或协会默认公众号。':'可以从草稿开始，填写计划与支持需求后再发布。'}</p></div><div className="admin-actions"><button className="admin-button admin-secondary" onClick={onReload}><RefreshCw size={16}/>刷新</button><button className="admin-button admin-primary" onClick={()=>edit(isActivity?{...emptyActivity}:{...emptyProject})}><Plus size={17}/>新建{isActivity?'活动':'项目'}</button></div></div><div className="admin-tabs">{[{v:'all',l:'全部'},{v:'published',l:'已发布'},{v:'draft',l:'草稿'}].map(tab=><button key={tab.v} className="admin-button admin-secondary" data-active={filter===tab.v} onClick={()=>setFilter(tab.v)}>{tab.l}</button>)}</div>{!shown.length?<div className="admin-empty"><h3>{isActivity?'还没有相关活动':'尚未添加攀登项目'}</h3><p>点击新建，开始填写内容。</p></div>:<div className="admin-record-list">{shown.map(item=><div className="admin-record-row" key={item.id}>{item.image?<img src={item.image} alt="封面"/>:<div className="admin-record-placeholder"><Image size={23}/></div>}<div><h3>{item.title}</h3><p className="admin-help">{isActivity?`${(item as Activity).date} · ${(item as Activity).kind==='upcoming'?'活动预告':'活动回顾'}`:(item as Project).mountain||'山峰目标待完善'}</p><span className="admin-status">{item.status==='published'?'已发布':'草稿'}</span>{item.isDemo&&<span className="admin-status">示意内容</span>}</div><div className="admin-actions">{item.status==='published'&&<a className="admin-icon-button" href={`/${isActivity?'activities':'projects'}/${item.id}`} target="_blank" rel="noopener noreferrer" aria-label={`查看${item.title}`}><ExternalLink size={18}/></a>}<button className="admin-icon-button" aria-label={`编辑${item.title}`} onClick={()=>edit(item)}><Pencil size={18}/></button><button className="admin-icon-button admin-danger" aria-label={`删除${item.title}`} disabled={busy} onClick={()=>void remove(item)}><Trash2 size={18}/></button></div></div>)}</div>}
  {editing&&<div ref={modalRef} onKeyDown={modalKeys} className="admin-modal" role="dialog" aria-modal="true" aria-label={isActivity?'编辑活动':'编辑攀登项目'}><div className="admin-modal-card"><div className="admin-toolbar"><h2>{editing.id?'编辑':'新建'}{isActivity?'活动':'攀登项目'}</h2><button className="admin-icon-button" aria-label="关闭编辑" onClick={close}><X size={22}/></button></div><form className="admin-form" data-dirty={dirty} onSubmit={save}>{field('标题','title',{required:true})}<div className="admin-grid"><label className="admin-field">发布状态<select value={editing.status} onChange={e=>update('status',e.target.value)}><option value="draft">草稿，仅获授权人员可见</option><option value="published">已发布，前台可见</option></select></label><label className="admin-check"><input type="checkbox" checked={editing.isDemo} onChange={e=>update('isDemo',e.target.checked)}/>这是示意内容</label></div>{isActivity?<><div className="admin-grid"><label className="admin-field">活动类型<select value={(editing as Activity).kind} onChange={e=>update('kind',e.target.value)}><option value="upcoming">未来活动预告</option><option value="past">近期活动回顾</option></select></label>{field('活动日期','date',{required:true,type:'date'})}{field('活动类别','category')}{field('地点 / 路线','location')}{field('难度 / 参与要求','difficulty')}</div><label className="admin-check"><input type="checkbox" checked={(editing as Activity).registrationOpen===true} onChange={e=>update('registrationOpen',e.target.checked)}/><span>开放社员报名<small className="admin-registration-help">仅已发布的未来正式活动接受报名。示例、过往活动和草稿均不接受报名。</small></span></label></>:<div className="admin-grid">{field('目标山峰','mountain')}{field('海拔','elevation')}{field('计划时间','plannedDate')}{field('项目周期','duration')}</div>}{field('简短摘要','summary',{textarea:true})}<ImageField label="封面图片" value={editing.image} onChange={v=>update('image',v)} onError={setFormError} onBusy={trackUpload} canUpload={canUpload}/>{field(isActivity?'活动安排 / 回顾正文':'攀登目标与计划','description',{textarea:true})}{isActivity?<><p className="admin-help">留空则使用协会设置中的公众号入口；请填写公众号正式活动推送或报名地址。</p>{field('公众号报名链接','signupUrl')}<ImageField label="报名二维码" value={(editing as Activity).qrImage} onChange={v=>update('qrImage',v)} onError={setFormError} onBusy={trackUpload} canUpload={canUpload}/></>:<>{field('训练与准备','trainingPlan',{textarea:true})}{field('支持需求','supportNeeds',{textarea:true})}{field('合作价值与方式','cooperationValue',{textarea:true})}</>}{formError&&<div role="alert" className="admin-alert">{formError}<p>如提示版本冲突，请先复制未保存内容，关闭编辑后刷新最新数据。</p></div>}<div className="admin-actions"><button className="admin-button admin-primary" disabled={busy||uploads>0}>{busy?'正在保存…':uploads?'等待上传完成…':'保存内容'}</button><button type="button" className="admin-button admin-secondary" onClick={close}>取消</button></div></form></div></div>}
  </section>;
}
